In [111]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [112]:
my_string1 = 'Bienvenido a'
my_string2 = "la nacho"
print(my_string1 + ' ' + my_string2)

Bienvenido a la nacho


In [113]:
my_int = 10
print(my_int)

print(type(my_int))

10
<class 'int'>


In [114]:
my_int = 32
print(my_int)

print(type(my_int))

32
<class 'int'>


In [115]:
my_string = "100"
print(type(my_string))

my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [116]:
my_string = "432"
print(type(my_string))

my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [117]:
my_float = 1.0
print(type(my_float))

my_int = 1
print(type(my_int))


<class 'float'>
<class 'int'>


In [118]:
my_float = 2.6
print(type(my_float))

my_int = 4
print(type(my_int))

<class 'float'>
<class 'int'>


In [119]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))


<class 'float'>


In [120]:
my_string = "132"
my_float = float(my_string)
print(type(my_float))


<class 'float'>


In [121]:
my_bool = False
print(my_bool)

print(type(my_bool))


False
<class 'bool'>


In [122]:
my_bool = True
print(my_bool)

print(type(my_bool))

True
<class 'bool'>


In [123]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [124]:
print("Addition ", 7+4)
print("Subtraction ", 3-7)
print("Multiplication ", 8*3)
print("Division", 10/7)
print("exponent", 5**3)

Addition  11
Subtraction  -4
Multiplication  24
Division 1.4285714285714286
exponent 125


In [125]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [126]:
my_list = ['la', 'nacho', 2,4,6]
print(my_list)

['la', 'nacho', 2, 4, 6]


In [127]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))

print(my_list[0])

print(my_list[len(my_list) - 1])


5
Quant
3


In [128]:
my_list = ['la', 'nacho', 2,4,6]
print(len(my_list))

print(my_list[0])

print(my_list[len(my_list) - 1])

5
la
6


In [129]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [130]:
my_list = ['la','nacho',1,2,3]
my_list[2] = 'llegar'
print(my_list)

['la', 'nacho', 'llegar', 2, 3]


In [131]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [132]:
my_list = ['la','nacho',1,2,3]
print(my_list[1:3])

['nacho', 1]


In [133]:
print(my_list[1:])

['nacho', 1, 2, 3]


In [134]:
print(my_list[2:])

[1, 2, 3]


In [135]:
print(my_list[:3])

['la', 'nacho', 1]


In [136]:
print(my_list[:4])

['la', 'nacho', 1, 2]


In [137]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)

my_list.remove('Hello')
print(my_list)


['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [138]:
my_list = ['Hola', 'unal']
my_list.append('hermosa')
print(my_list)

my_list.remove('Hola')
print(my_list)

['Hola', 'unal', 'hermosa']
['unal', 'hermosa']


In [139]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [140]:
my_tuple = ('Bienvenido','a','unal')
print(my_tuple[1:])

('a', 'unal')


In [141]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'AAPL', 'F', 'GOOG', 'FB', 'IBM'}


In [142]:
stock_list = ['ADD','APP','IBM','GOOO','ADD','FB','WP','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'APP', 'GOOO', 'GOOG', 'FB', 'ADD', 'WP', 'IBM'}


In [143]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}

In [144]:
print(my_dic['GOOG'])

Alphabet


In [145]:
my_dic = {'ADD': 'Añadir', 'FB': 'FaceBook', 'APP': 'Aplicacion'}

In [146]:
print(my_dic['ADD'])

Añadir


In [147]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [19]:
my_dic['WP'] = 'Well Played'
print(my_dic['WP'])

Well Played


In [ ]:
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [20]:
print(my_dic.keys())

dict_keys(['ADD', 'FB', 'APP', 'WP'])


In [ ]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [21]:
my_str = 'bienvenido a la unal'
print(my_str[8:])

do a la unal


In [ ]:
print("Counting the number of e's in this sentence".count('e'))

print('The first time e appears in this sentence'.find('e'))

print('all the a in this sentence now becomes e'.replace('a','e'))


6
2
ell the e in this sentence now becomes e


In [25]:
print("Buscando letras en la oracion".count('a'))

print('cual es la primera aparicion de e'.find('e'))

print('a ti te da ansiedad'.replace('a','e'))


4
5
e ti te de ensieded


In [ ]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

hour = time.split(':')[0]
print(hour)


2016-04-01 09:43:00
09


In [26]:
Time = '2021-10-20 09:00:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

hour = time.split(':')[0]
print(hour)

2021-10-20 09:00:00
09


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)


Hour: 9, Minute: 43


In [28]:
my_time = 'Hour: {}, Minute: {}'.format(10, 23)
print(my_time)


Hour: 10, Minute: 23


In [ ]:
print ('pi is %f' % 3.14)

print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [29]:
print ('pi is %f' % 2.71)

print('%s to %s' % ('Bienvenido', 'compañero'))

pi is 2.710000
Bienvenido to compañero


##2. LOGICAL OPERATIONS

In [ ]:
print (1 == 0)    # 1 equals 0
print (1 == 1)    # 1 equals 1
print (1 != 0)    # 1 is not equal to 0
print (5 >= 5)    # 5 is greater than or equal to 5
print (5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [30]:
print (5 == 0)    
print (5 == 5)    
print (5 != 0)    
print (5 >= 5)    
print (5 >= 6)    

False
True
True
True
False


In [31]:
print (2 > 1 and 3 > 2)
print (2 > 1 and 3 < 2)
print (2 > 1 or  3 < 2)
print (2 < 1 and 3 < 2)

False
True
True
False


In [32]:
print (4 > 1 and 3 > 4)
print (4 > 1 and 3 < 4)
print (4 > 1 or  3 < 4)
print (4 < 1 and 3 < 4)

False
True
True
False


In [ ]:
print ((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print (3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


In [33]:
print ((5 > 2 or 1 < 5) and (1!=5 and 4>5) and not ( 5 < 2 or 1 < 5 and (1!=5 and 4>5)))
print (5 > 2 or 1 < 5 and (1!=5 and 4>5) and not ( 5 < 2 or 1 < 5 and (1!=5 and 4>5)))

False
True


In [ ]:
i = 0
if i == 0: print ('i == 0 is True')

i == 0 is True


In [34]:
i = 5
if i == 5: print ('i == 5 is True')

i == 5 is True


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print ('p and q is true')
elif p and not q:
    print ('q is false')
elif q and not p:
    print ('p is false')
else:
    print ('None of p and q is true')

q is false


In [36]:
p = 5 > 1
q = 3 > 2
if p and q:
    print ('p and q is true')
elif p and not q:
    print ('q is false')
elif q and not p:
    print ('p is false')
else:
    print ('None of p and q is true')

p and q is true


In [ ]:
i = 0
while i < 5:
    print( i)
    i += 1

0
1
2
3
4


In [38]:
i = 3
while i > 0:
    print( i)
    i -= 1

3
2
1


In [ ]:
for x in [1,2,3,4,5]: print (x)

1
2
3
4
5


In [39]:
for x in [1,2,3,4,5,6,7,8,9]: print (x)

1
2
3
4
5
6
7
8
9


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print (new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [40]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM','GOOG','F']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print (new_list)

['FB', 'V', 'G', 'GE']


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [41]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'F': break

AAPL
GOOG
IBM
FB
F


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print (stock)

AAPL
GOOG
IBM
F
V
G
GE


In [42]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'IBM': continue
    print (stock)

AAPL
GOOG
FB
F
V
G
GE


In [ ]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print (squares)

[1, 4, 9, 16, 25]


In [43]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**3)
print (squares)

[1, 8, 27, 64, 125]


In [ ]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print (squares)

[1, 4, 9, 16, 25]


In [44]:
foo = [1,2,3,4,5]
squares = [x**3 for x in foo]
print (squares)

[1, 8, 27, 64, 125]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [45]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM','FB']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['GOOG', 'F', 'V', 'G', 'GE']


In [ ]:
print ([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [46]:
print ([(x, y) for x in [1,2,3] for y in [3,1,2] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','F']
                                for y in ['FB','V','G','GE'] if x != y])

[(1, 3), (1, 2), (2, 3), (2, 1), (3, 1), (3, 2)]
['AAPL vs FB', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs FB', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs FB', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'F vs FB', 'F vs V', 'F vs G', 'F vs GE']


## 3. Functions

In [47]:
def product(x,y):
    return x*y
print (product(2,3))

print (product(5,10))


6
50


In [48]:
def product(x,y):
    return x*y
print (product(2,6))

print (product(4,10))

12
40


In [ ]:
def say_hi():
    print ("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [49]:
def say_hi():
    print ("Bienvenido a la unal")
say_hi()

Bienvenido a la unal


In [ ]:
print (range(10))

print (range(1, 11))

print (range(1, 11, 2))


range(0, 10)
range(1, 11)
range(1, 11, 2)


In [50]:
print (range(7))

print (range(1, 8))

print (range(1, 8, 3))

range(0, 7)
range(1, 8)
range(1, 8, 3)


In [ ]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print ("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [51]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE', 'WP','R']
print ("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

The number of tickers is 10
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE
9 WP
10 R


In [ ]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [52]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE','WP','R']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2, 2, 1]


In [53]:
map(lambda x: x**2, range(10))  

In [54]:
map(lambda x: x**2, range(8))  

In [55]:
map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1]) 

In [56]:
map(lambda x, y: x+y, [1,2,3,4,5,6], [5,4,3,2,1,0]) 

In [ ]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [57]:
sorted([5,2,3,4,6,1])

[1, 2, 3, 4, 5, 6]

In [ ]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [59]:
price_list = [('AAPL', 150.09), ('GOOGL', 971.71), ('MSFT', 691), ('FB', 10), ('WMT', 5.32)]
sorted(price_list, key = lambda x: x[1])

[('WMT', 5.32), ('FB', 10), ('AAPL', 150.09), ('MSFT', 691), ('GOOGL', 971.71)]

In [61]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [62]:
price_list = [('AAPL', 150.09), ('GOOGL', 971.71), ('MSFT', 691), ('FB', 10), ('WMT', 5.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 971.71), ('MSFT', 691), ('AAPL', 150.09), ('FB', 10), ('WMT', 5.32)]

In [ ]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [63]:
price_list = [('AAPL', 150.09), ('GOOGL', 971.71), ('MSFT', 691), ('FB', 10), ('WMT', 5.32)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('WMT', 5.32), ('FB', 10), ('AAPL', 150.09), ('MSFT', 691), ('GOOGL', 971.71)]


In [65]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print (self.rate_return)

In [66]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [67]:
apple.ticker

google.print_return()

google.update(912.8,913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


In [68]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [69]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [70]:
apple  = Stock('AAPL', 14.69, 144.09, 20109375)
google = Stock('GOOGL', 834.7, 911.7, 1561616)

In [71]:
apple.ticker

google.print_return()

google.update(43.8,913.4)
google.print_return()

0.09224871211213603
19.853881278538815


In [72]:
apple.ceo = 'Cosita'
apple.ceo

'Cosita'

In [73]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [74]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [ ]:
aa = Child('AA')
print (aa.name)

aa.update(100, 102)
print (aa.open)

print (aa.close)

print (aa.print_return())


AA
100
102
0.020000000000000018
None


In [75]:
aa = Child('AAA')
print (aa.name)

aa.update(10, 1042)
print (aa.open)

print (aa.close)

print (aa.print_return())

AAA
10
1042
103.2
None


## 4. NumPy

In [77]:
import numpy as np

In [78]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print (price_array, type(price_array))



[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [79]:
price_list = [14.73, 155.83, 343.68, 654.02, 43.5, 97.62]
price_array = np.array(price_list)
print (price_array, type(price_array))

[ 14.73 155.83 343.68 654.02  43.5   97.62] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3], [2,4]])
print (Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
print (Ar.shape)

(2, 2)


In [ ]:
print (Ar[0])

print (Ar[1])

[1 3]
[2 4]


In [ ]:
print ('First column:', Ar[:,0])

print ('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [ ]:
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [ ]:
print (np.mean(price_array))

print (np.std(price_array))

print (np.sum(price_array))

print (np.max(price_array))


143.89666666666668
0.9673790478515796
863.38
145.83


In [80]:
Ar = np.array([[1,5], [2,4]])
print (Ar, type(Ar))

[[1 5]
 [2 4]] <class 'numpy.ndarray'>


In [81]:
print (Ar.shape)

(2, 2)


In [86]:
print (Ar[0])

print (Ar[1])

[1 5]
[2 4]


In [84]:
print ('First column:', Ar[:,0])

print ('Second column:', Ar[:,1])

First column: [1 2]
Second column: [5 4]


In [88]:
np.log(price_array)

array([2.68988623, 5.04876567, 5.83971099, 6.48313793, 3.77276094,
       4.58108239])

In [87]:
print (np.mean(price_array))

print (np.std(price_array))

print (np.sum(price_array))

print (np.max(price_array))

218.23000000000002
222.12383242987082
1309.38
654.02


## Pandas

In [89]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print (s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [ ]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print (s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print (s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
print (s[1:])
print (s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [ ]:
print (s[4])
s[4] = 0
print (s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [ ]:
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [ ]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [ ]:
print (s.iloc[1])

145.83


In [ ]:
s.index = time_index
print (s['2017-01-03'])

143.68


In [ ]:
print (s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [90]:
price = [1465.73, 1465.83, 1465.68, 1466.02, 143.5, 142.62]
s = pd.Series(price)
print (s)

0    1465.73
1    1465.83
2    1465.68
3    1466.02
4     143.50
5     142.62
dtype: float64


In [92]:
s = pd.Series(price, index = ['a', 'c', 'e', 'f','g','h'])
print (s)

a    1465.73
c    1465.83
e    1465.68
f    1466.02
g     143.50
h     142.62
dtype: float64


In [93]:
s.index = [6,5,4,3,2,1]
print (s)

6    1465.73
5    1465.83
4    1465.68
3    1466.02
2     143.50
1     142.62
dtype: float64


In [95]:
print (s[1:])
print (s[:-3])

5    1465.83
4    1465.68
3    1466.02
2     143.50
1     142.62
dtype: float64
6    1465.73
5    1465.83
4    1465.68
dtype: float64


In [98]:
print (s[5])
s[5] = 0
print (s)

1465.83
6    1465.73
5       0.00
4       0.00
3    1466.02
2     143.50
1     142.62
dtype: float64


In [99]:
s = pd.Series(price, name = 'unal price')
print (s)
print (s.name)

0    1465.73
1    1465.83
2    1465.68
3    1466.02
4     143.50
5     142.62
Name: unal price, dtype: float64
unal price


In [100]:
print (s.describe())

count       6.000000
mean     1024.896667
std       683.067811
min       142.620000
25%       474.045000
50%      1465.705000
75%      1465.805000
max      1466.020000
Name: unal price, dtype: float64


In [101]:
time_index = pd.date_range('2021-10-20', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)

DatetimeIndex(['2021-10-20', '2021-10-21', '2021-10-22', '2021-10-23',
               '2021-10-24', '2021-10-25'],
              dtype='datetime64[ns]', freq='D')
2021-10-20    1465.73
2021-10-21    1465.83
2021-10-22    1465.68
2021-10-23    1466.02
2021-10-24     143.50
2021-10-25     142.62
Freq: D, Name: unal price, dtype: float64


In [103]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[2])

6    1465.73
5    1465.83
4    1465.68
3    1466.02
2     143.50
1     142.62
Name: unal price, dtype: float64
143.5


In [105]:
print (s.iloc[2])

1465.68


In [108]:
s.index = time_index
print (s['2021-10-20'])

1465.73


In [109]:
print (s['2020-10-20':'2020-10-22'])

Series([], Freq: D, Name: unal price, dtype: float64)


In [110]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2021-10-24    143.50
2021-10-25    142.62
Freq: D, Name: unal price, dtype: float64
2021-10-20    1465.73
2021-10-21    1465.83
2021-10-22    1465.68
2021-10-23    1466.02
Freq: D, Name: unal price, dtype: float64
